const initData = {
  lat: "",
  lon: "",
  timezone: "",
  timezone_offset: "",
  current: {
    dt: 0,
    sunrise: 0,
    sunset: 0,
    temp: "",
    feels_like: "",
    pressure: "",
    humidity: "",
    dew_point: "",
    uvi: "",
    clouds: "",
    visibility: "",
    wind_speed: "",
    wind_deg: "",
    wind_gust: "",
    weather: [
      {
        id: "",
        main: "",
        description: "",
        icon: "",
      },
    ],
  },
  minutely: [
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
    {
      dt: "",
      precipitation: "",
    },
  ],
  hourly: [
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
      rain: {
        "1h": "",
      },
    },
    {
      dt: "",
      temp: "",
      feels_like: "",
      pressure: "",
      humidity: "",
      dew_point: "",
      uvi: "",
      clouds: "",
      visibility: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      pop: "",
    },
  ],
  daily: [
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      rain: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      rain: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      uvi: "",
    },
    {
      dt: "",
      sunrise: "",
      sunset: "",
      moonrise: "",
      moonset: "",
      moon_phase: "",
      temp: {
        day: "",
        min: "",
        max: "",
        night: "",
        eve: "",
        morn: "",
      },
      feels_like: {
        day: "",
        night: "",
        eve: "",
        morn: "",
      },
      pressure: "",
      humidity: "",
      dew_point: "",
      wind_speed: "",
      wind_deg: "",
      wind_gust: "",
      weather: [
        {
          id: "",
          main: "",
          description: "",
          icon: "",
        },
      ],
      clouds: "",
      pop: "",
      uvi: "",
    },
  ],
};

export default initData

